### ISSUE TITLE
make -j4 error

### ISSUE THREAD

**Issue by raclab** [vss2sn/tello#1]
$ make -j4
Scanning dependencies of target joystick
Scanning dependencies of target utils
Scanning dependencies of target h264decoder
[  6%] Building CXX object CMakeFiles/joystick.dir/lib_joystick/joystick.cpp.o
[ 20%] Building CXX object CMakeFiles/h264decoder.dir/lib_h264decoder/h264decoder.cpp.o
[ 20%] Building CXX object CMakeFiles/utils.dir/lib_utils/utils.cpp.o
[ 26%] Linking CXX shared library libh264decoder.so
[ 33%] Linking CXX shared library libutils.so
[ 33%] Built target utils
[ 33%] Built target h264decoder
[ 40%] Linking CXX shared library libjoystick.so
[ 40%] Built target joystick
Scanning dependencies of target tello
[ 66%] Building CXX object CMakeFiles/tello.dir/main/main.cpp.o
[ 66%] Building CXX object CMakeFiles/tello.dir/src/state_socket.cpp.o
[ 66%] Building CXX object CMakeFiles/tello.dir/src/base_socket.cpp.o
[ 66%] Building CXX object CMakeFiles/tello.dir/src/tello.cpp.o
In file included from /home/raclab/Documents/tello/inc/tello.hpp:7:0,
                 from /home/raclab/Documents/tello/main/main.cpp:5:
/home/raclab/Documents/tello/inc/video_socket.hpp:97:29: error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’
   std::atomic<bool> snap_ = false;
                             ^
In file included from /home/raclab/Documents/tello/inc/tello.hpp:7:0,
                 from /home/raclab/Documents/tello/src/tello.cpp:3:
/home/raclab/Documents/tello/inc/video_socket.hpp:97:29: error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’
   std::atomic<bool> snap_ = false;
                             ^
In file included from /usr/include/asio/detail/atomic_count.hpp:23:0,
                 from /usr/include/asio/detail/task_io_service.hpp:24,
                 from /usr/include/asio/impl/io_service.hpp:69,
                 from /usr/include/asio/io_service.hpp:765,
                 from /usr/include/asio/basic_io_object.hpp:19,
                 from /usr/include/asio/basic_socket.hpp:20,
                 from /usr/include/asio/basic_datagram_socket.hpp:20,
                 from /usr/include/asio.hpp:19,
                 from /home/raclab/Documents/tello/inc/base_socket.hpp:5,
                 from /home/raclab/Documents/tello/inc/command_socket.hpp:10,
                 from /home/raclab/Documents/tello/inc/tello.hpp:6,
                 from /home/raclab/Documents/tello/src/tello.cpp:3:
/usr/include/c++/5/atomic:66:5: note: declared here
     atomic(const atomic&) = delete;
     ^
In file included from /usr/include/asio/detail/atomic_count.hpp:23:0,
                 from /usr/include/asio/detail/task_io_service.hpp:24,
                 from /usr/include/asio/impl/io_service.hpp:69,
                 from /usr/include/asio/io_service.hpp:765,
                 from /usr/include/asio/basic_io_object.hpp:19,
                 from /usr/include/asio/basic_socket.hpp:20,
                 from /usr/include/asio/basic_datagram_socket.hpp:20,
                 from /usr/include/asio.hpp:19,
                 from /home/raclab/Documents/tello/inc/base_socket.hpp:5,
                 from /home/raclab/Documents/tello/inc/command_socket.hpp:10,
                 from /home/raclab/Documents/tello/inc/tello.hpp:6,
                 from /home/raclab/Documents/tello/main/main.cpp:5:
/usr/include/c++/5/atomic:66:5: note: declared here
     atomic(const atomic&) = delete;
     ^
/usr/include/c++/5/atomic:70:15: note:   after user-defined conversion: constexpr std::atomic<bool>::atomic(bool)
     constexpr atomic(bool __i) noexcept : _M_base(__i) { }
               ^
/usr/include/c++/5/atomic:70:15: note:   after user-defined conversion: constexpr std::atomic<bool>::atomic(bool)
     constexpr atomic(bool __i) noexcept : _M_base(__i) { }
               ^
CMakeFiles/tello.dir/build.make:62: recipe for target 'CMakeFiles/tello.dir/main/main.cpp.o' failed
make[2]: *** [CMakeFiles/tello.dir/main/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/tello.dir/build.make:110: recipe for target 'CMakeFiles/tello.dir/src/tello.cpp.o' failed
make[2]: *** [CMakeFiles/tello.dir/src/tello.cpp.o] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/tello.dir/all' failed
make[1]: *** [CMakeFiles/tello.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I got above error when make -j4. Why?

**Comment by vss2sn** [comment]
Check whether your compiler is using c++17. This is an error seen with c++14; setting `add_definitions(-std=c++14)` reproduces this error. If not, could you mention any changes you made to the `CMakeLists.txt`? 

Another solution might be to change `std::atomic<bool> snap_ = false; ` to `std::atomic<bool> snap_ {false};`

**Comment by raclab** [comment]
Thank you for helping. It works now.
