### ISSUE TITLE
OpenVSLAM Released a Termination Due to Copy Right Issues with ORB-SLAM2

### ISSUE THREAD

**Issue by samehmohamed88** [vss2sn/tello#8]
Just came across this wiki page on OpenVSLAM Github repo

https://github.com/xdspacelab/openvslam/wiki/Termination-of-the-release

I may explore using ORB-SLAM2 instead open openvlsam for this project.  If I were to do so, would you have the time to verify a PR for that?

**Comment by vss2sn** [comment]
I'd be happy to verify the PR; this has been on my todo list for a while.
